name: flink
lang: java
lang_version: 8
git:
  enable: true
github:
  enable: true
  repo_name: confluentinc/flink
semaphore:
  enable: true
  triggers: ['branches', 'pull_requests']
  branches:
    - master
    - main
    - /^release-\d+\.\d+-confluent$/
  schedulers:
    - name: Sync Apache Flink Branches
      branch: master
      at: "*/15 * * * *"
      pipeline_file: .semaphore/apache-flink-sync.yml
    - name: Sync Apache to Confluent Branches
      branch: master
      at: "0 8 * * MON"
      pipeline_file: .semaphore/apache-confluent-sync.yml
