name: flink
lang: java
lang_version: 8
git:
  enable: true
github:
  enable: true
  repo_name: confluentinc/flink
semaphore:
  enable: true
  schedulers:
    - name: Sync Apache Flink Branches
      branch: master
      at: "*/15 * * * *"
      pipeline_file: .semaphore/apache-flink-sync.yml
